### PR TITLE
Feature/dvc

### PR DESCRIPTION
**Pull request by Miautawn**
Add DVC to this repository

Things implemented with this pull request:
- A google drive remote
- A script, that download the dataset zip file and then extracts it

### CODE REVIEW

**Comment by Miautawn** [comment]
Note: when using the data downloading script or the ```dvc pull``` command, you will probably be prompted to authenticate your google drive (for whatever reason). You have to check both permission boxes in the provided auth window. 

We will need to discuss where we will be keeping our data.

**Comment by jgamper** [comment]
> Note: when using the data downloading script or the `dvc pull` command, you will probably be prompted to authenticate your google drive (for whatever reason). You have to check both permission boxes in the provided auth window.
> 
> We will need to discuss where we will be keeping our data.

@Miautawn regarding where to keep the data. I suggest to download data via dropbox link I've shared. https://www.dropbox.com/s/if42duiggv5am29/diplomacy-v1-27k-msgs.zip?dl=0 just change zero to 1 and it will download the file directly. The download of the data could be a first step in the dvc dag. What do you think?

**Comment by Miautawn** [comment]
"just change zero to 1 and it will download the file directly" - this is probably why it did not work for me. I'll try it again and share on the results.

**Comment by Miautawn** [comment]
> "just change zero to 1 and it will download the file directly" - this is probably why it did not work for me. I'll try it again and share on the results.

Success! I'll redo the script :)

**Pull request merged**
